apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://susanabm.github.io/demo-api-helm/  # GitHub Pages del chart
    chart: demo-chart                                        # nombre del chart
    targetRevision: 0.1.1
    helm:
      values: |
        replicaCount: 2
        image:
          repository: demoapiregistry.azurecr.io/demo-api
          tag: latest
        postgresql:
          auth:
            username: demo_user
            password: demo_pass
            database: pedidosdb
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
