project: default
source:
  repoURL: https://github.com/SusanaBM/k8sRepository.git
  path: K8s
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: demo-api
syncPolicy:
  automated:
    enabled: true
  syncOptions:
    - CreateNamespace=true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://susanabm.github.io/demo-api-helm/  # GitHub Pages del chart
    chart: demo-chart                                        # nombre del chart
    targetRevision: 0.1.0                                    # versión del .tgz en docs/index.yaml
    helm:
      values: |
        replicaCount: 2
        image:
          repository: demoapiregistry.azurecr.io/demo-api
          tag: latest
        postgresql:
          auth:
            username: demo_user
            password: demo_pass
            database: pedidosdb
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
