apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagfinal }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-connection
                  key: connectionstring
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-config
                  key: APP_ENV
            
