apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-migrations
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ef-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagmigration }}"
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.key }}
          command:
            - /bin/sh
            - -c
            - |
              dotnet tool restore && \
              dotnet ef database update --project {{ .Values.app.project }} --startup-project {{ .Values.app.project }} --verbose