apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-connection
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
type: Opaque
stringData:
  connectionstring: |
    Host={{ .Release.Name }}-postgresql;
    Port=5432;
    Database={{ .Values.postgresql.auth.database }};
    Username={{ .Values.postgresql.auth.username }};
    Password={{ .Values.postgresql.auth.password }};
    Ssl Mode={{ .Values.connection.sslMode }};